using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
   {
    


     private float speed = 20.0f;
    private float turnSpeed = 45.0f;
    private float horizontalInput;
    private float forwardInput;
    //public Vector3 rotationCar = RotationCar();
    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        horizontalInput = Input.GetAxis("Horizontal");
        forwardInput = Input.GetAxis("Vertical");
        // Moves car forwards
        transform.Translate(Vector3.back * Time.deltaTime * speed * forwardInput);
        // rotates car
        transform.Rotate(Vector3.up, turnSpeed * horizontalInput * Time.deltaTime);
        //rotationCar = RotationCar();
        
    }
    
    //Vector3 RotationCar()
    //{
      // rotates the car
      //transform.Rotate(Vector3.up, turnSpeed * horizontalInput * Time.deltaTime);


    //}
   
   }
